const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ROOT=document.body.dataset.root||'../../',CLIENT=document.body.dataset.client||'lavareda';
const ICONS={inicio:'⌂',conteudos:'▤',calendario:'□',arquivos:'⌁'};
const NAV=[['inicio','Início'],['conteudos','Conteúdos'],['calendario','Calendário'],['arquivos','Arquivos']];
const DEMO_MEDIA={
  'HO-01':{type:'reel',label:'REEL',aspect:'9/16'},
  'KP-01':{type:'static',label:'ESTÁTICO',image:'1eOFPH5mYWFv79zhxC5VorGKnzVTCrXNx',title:'Gravidez de alto risco e benefício por incapacidade sem carência',date:'2026-09-02'},
  'VM-01':{type:'carousel',label:'CARROSSEL',slides:['1r0fQRijZaMmrAVP1fgREq8EV_buNi6mt','1x_cx2gtECzvErlIPn8NQZQctH_EISNk_','1BOyJ9LsMl-ualKIDUBfc9n673SLkWaKN','1iLIKAe9yRRWAc_O7fVaHoxtn-BKO1L7r','1H4_yLgSdLAgOq9OELij0oqCP2SRZowCW'],title:'Cônjuge separado e dependência econômica para pensão militar',date:'2026-09-04'}
};
const state={config:null,contents:[],actions:[],page:'inicio',reviewId:null,lot:'',carouselIndex:{},feedbackOpen:false};
function mediaFor(c){return DEMO_MEDIA[c.id]||{type:'reel',label:'REEL',aspect:(c.videoWidth&&c.videoHeight)?`${c.videoWidth}/${c.videoHeight}`:'9/16'}}
function display(c){const m=mediaFor(c);return {...c,title:m.title||c.title,date:m.date||c.date,media:m}}
function thumbId(id){return `https://drive.google.com/thumbnail?id=${id}&sz=w1600`}
function thumb(c){const d=display(c);if(d.media.type==='static')return thumbId(d.media.image);if(d.media.type==='carousel')return thumbId(d.media.slides[0]);return `https://drive.google.com/thumbnail?id=${c.coverId||c.videoId}&sz=w1000`}
function videoUrl(c){return `https://drive.google.com/file/d/${c.videoId}/preview`}
function setTheme(mode){localStorage.setItem('audaz-theme',mode);applyTheme()}
function applyTheme(){const pref=localStorage.getItem('audaz-theme')||'system';const resolved=pref==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):pref;document.documentElement.dataset.theme=resolved;$$('[data-theme-mode]').forEach(b=>b.classList.toggle('active',b.dataset.themeMode===pref));document.querySelector('meta[name=theme-color]')?.setAttribute('content',resolved==='dark'?'#151514':'#e8e4d6')}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function statusFor(c){let s=c.initialStatus||'aguardando';state.actions.filter(a=>a.contentId===c.id).forEach(a=>{if(a.action==='APROVADO')s='aprovado';if(a.action==='ALTERACAO')s='alteracao'});return s}
function statusLabel(s){return s==='aprovado'?'Aprovado':s==='alteracao'?'Em alteração':'Aguardando você'}
function statusBadge(c){const s=statusFor(c);return `<span class="status ${s}"><i></i>${statusLabel(s)}</span>`}
function dateObj(d){if(!d)return null;const [y,m,day]=d.split('-').map(Number);return new Date(y,m-1,day)}
function dateLong(d){const x=dateObj(d);return x?x.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}):''}
function dayDiff(d){const x=dateObj(d);if(!x)return null;const n=new Date();n.setHours(0,0,0,0);x.setHours(0,0,0,0);return Math.round((x-n)/86400000)}
function urgency(c){const d=display(c),n=dayDiff(d.date);if(n===0)return'Publicação prevista para hoje';if(n===1)return'Publicação prevista para amanhã';if(n>1&&n<=7)return`Publicação em ${n} dias`;return d.date?`Previsto para ${dateLong(d.date)}`:''}
function renderNav(){const h=NAV.map(([id,l])=>`<button class="nav-btn ${state.page===id?'active':''}" data-nav="${id}"><span class="nav-icon">${ICONS[id]}</span>${l}</button>`).join('');$('#sideNav').innerHTML=h;$('#drawerNav').innerHTML=h}
function bindBase(){document.body.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);return}const rev=e.target.closest('[data-review]');if(rev){openReview(rev.dataset.review);return}});$('#mobileMenu').onclick=()=>$('#drawer').classList.add('show');$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('show');$('#drawer').onclick=e=>{if(e.target===$('#drawer'))$('#drawer').classList.remove('show')};$$('[data-theme-mode]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeMode));$('#mobileTheme').onclick=()=>{const cur=localStorage.getItem('audaz-theme')||'system';setTheme(cur==='system'?'light':cur==='light'?'dark':'system')}}
function navigate(page){state.page=page;state.reviewId=null;state.feedbackOpen=false;$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));renderNav();$('#drawer').classList.remove('show');renderPage(page);window.scrollTo({top:0,behavior:'smooth'})}
function openReview(id){state.reviewId=id;state.feedbackOpen=false;$$('.page').forEach(p=>p.classList.remove('active'));$('#page-revisao').classList.add('active');renderReview();window.scrollTo({top:0,behavior:'smooth'})}
function stats(){const total=state.contents.length,waiting=state.contents.filter(c=>statusFor(c)==='aguardando'),approved=state.contents.filter(c=>statusFor(c)==='aprovado'),changes=state.contents.filter(c=>statusFor(c)==='alteracao');return{total,waiting,approved,changes}}
function typeChip(c){const m=mediaFor(c);return `<span class="type-chip ${m.type}">${m.label}</span>`}
function pageHead(title,desc){return `<header class="page-head"><span>${state.lot||'CICLO ATUAL'}</span><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</header>`}
function contentRow(c){const d=display(c);return `<button class="content-row" data-review="${c.id}"><img src="${thumb(c)}" alt=""><span class="row-main">${typeChip(c)}<strong>${d.title}</strong><small>${d.person} · ${dateLong(d.date)}</small></span><span class="row-urgency">${urgency(c)}</span>${statusBadge(c)}<b class="row-action">${statusFor(c)==='aprovado'?'VER':'REVISAR'} →</b></button>`}
function renderInicio(){const s=stats(),focus=s.waiting.slice(0,4),pct=s.total?Math.round(s.approved.length/s.total*100):0;$('#page-inicio').innerHTML=`${pageHead(`Olá, ${state.config.name}.`,'Abra, confira e decida. Só isso.')}<section class="hero"><div><span class="eyebrow">PRECISAM DE VOCÊ</span><div class="hero-count">${s.waiting.length}</div><h2>${s.waiting.length===1?'conteúdo aguarda aprovação':'conteúdos aguardam aprovação'}</h2><p>${s.waiting.length?'Comece pelo primeiro e siga até terminar.':'Tudo certo. Nenhuma decisão pendente.'}</p>${s.waiting.length?`<button class="btn primary big" data-review="${s.waiting[0].id}">REVISAR AGORA →</button>`:''}</div><div class="progress-box"><div><span>PROGRESSO DO CICLO</span><strong>${pct}%</strong></div><div class="progress"><i style="width:${pct}%"></i></div><div class="numbers"><span><b>${s.approved.length}</b> aprovados</span><span><b>${s.changes.length}</b> em alteração</span><span><b>${s.total}</b> total</span></div></div></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">ORDEM DE REVISÃO</span><h3>${focus.length?'Comece por aqui':'Tudo revisado'}</h3></div><button class="link-btn" data-nav="conteudos">Ver todos →</button></div><div class="rows">${focus.map(contentRow).join('')||'<div class="empty">Você está em dia com este ciclo.</div>'}</div></section><footer class="partnership"><div><span>AUDAZ × ${state.config.name.toUpperCase()}</span><strong>${state.config.manifesto||'CONTEÚDO COM INTENÇÃO.'}</strong></div><p>${state.config.headline||''}</p></footer>`}
function renderConteudos(){const s=stats(),priority=[...s.waiting,...s.changes];$('#page-conteudos').innerHTML=`${pageHead('Conteúdos','Reels, estáticos e carrosséis no mesmo fluxo de aprovação.')}<section class="panel"><div class="panel-head"><div><span class="eyebrow">PRECISAM DE VOCÊ</span><h3>${priority.length} itens</h3></div></div><div class="rows">${priority.map(contentRow).join('')||'<div class="empty">Nada pendente.</div>'}</div></section><details class="approved"><summary>Aprovados · ${s.approved.length}<span>+</span></summary><div class="rows">${s.approved.map(contentRow).join('')}</div></details>`}
function reviewQueue(){const p=state.contents.filter(c=>statusFor(c)!=='aprovado');return p.length?p:state.contents}
function mediaViewer(c){const d=display(c),m=d.media;if(m.type==='static')return `<div class="image-stage"><img src="${thumbId(m.image)}" alt="${d.title}"></div>`;if(m.type==='carousel'){const idx=state.carouselIndex[c.id]||0,slide=m.slides[idx];return `<div class="carousel-view"><div class="carousel-main"><button class="carousel-arrow left" data-carousel-prev="${c.id}" ${idx===0?'disabled':''}>←</button><img src="${thumbId(slide)}" alt="Slide ${idx+1}"><button class="carousel-arrow right" data-carousel-next="${c.id}" ${idx===m.slides.length-1?'disabled':''}>→</button><span class="carousel-count">${idx+1} de ${m.slides.length}</span></div><div class="carousel-thumbs">${m.slides.map((id,i)=>`<button class="${i===idx?'active':''}" data-carousel-to="${c.id}" data-index="${i}"><img src="${thumbId(id)}" alt="Slide ${i+1}"></button>`).join('')}</div></div>`}const ratio=m.aspect||'9/16';return `<div class="video-stage" style="--ratio:${ratio.replace('/',' / ')}"><button class="video-launch" data-play="${c.id}"><span>▶</span><strong>Assistir vídeo</strong></button></div>`}
function renderDecision(c,next){const st=statusFor(c);return `<aside class="decision-card"><span class="eyebrow">SUA DECISÃO</span><h3>${st==='aprovado'?'Conteúdo aprovado':'Está tudo certo?'}</h3><p>${st==='alteracao'?'Sua solicitação já foi registrada. Você pode complementar se precisar.':'Se estiver tudo certo, aprove. Se precisar mudar algo, peça o ajuste.'}</p>${st!=='aprovado'?`<button class="btn primary wide" data-approve="${c.id}">✓ APROVAR</button><button class="btn wide" data-open-feedback="${c.id}">SOLICITAR ALTERAÇÃO</button>`:`<div class="done-box">✓ Aprovado</div>`}<div class="feedback-area ${state.feedbackOpen?'show':''}" id="feedbackArea"><label>O que precisa ser ajustado?</label><textarea id="reviewFeedback" placeholder="Ex.: aos 00:18, trocar a frase de abertura."></textarea><div class="feedback-actions"><button class="btn" data-cancel-feedback>CANCELAR</button><button class="btn primary" data-send-feedback="${c.id}">ENVIAR SOLICITAÇÃO</button></div></div>${next?`<button class="next-content" data-review="${next.id}">Próximo conteúdo →</button>`:''}</aside>`}
function renderReview(){const c=state.contents.find(x=>x.id===state.reviewId);if(!c)return navigate('conteudos');const d=display(c),q=reviewQueue(),pos=Math.max(0,q.findIndex(x=>x.id===c.id)),prev=q[pos-1],next=q[pos+1];$('#page-revisao').innerHTML=`<div class="review-top"><button data-nav="conteudos">← Sair da revisão</button><span><strong>${pos+1}</strong> de ${q.length}</span><div><button class="round" ${prev?`data-review="${prev.id}"`:'disabled'}>←</button><button class="round" ${next?`data-review="${next.id}"`:'disabled'}>→</button></div></div><header class="review-head">${statusBadge(c)} ${typeChip(c)}<h1>${d.title}</h1><p>${d.person} · ${dateLong(d.date)}</p><em>${urgency(c)}</em></header><div class="review-grid"><main class="review-content"><section class="media-card"><div class="media-head"><span>${d.media.label}</span><small>${d.media.type==='carousel'?'Passe pelos slides antes de decidir':'Confira a peça antes de decidir'}</small></div>${mediaViewer(c)}</section><section class="caption-card"><div class="media-head"><span>LEGENDA</span><button data-copy="${c.id}">COPIAR</button></div><div class="caption">${c.caption||'Legenda ainda não adicionada.'}</div></section></main>${renderDecision(c,next)}</div><div class="mobile-actions-bar">${statusFor(c)!=='aprovado'?`<button class="btn" data-open-feedback="${c.id}">PEDIR AJUSTE</button><button class="btn primary" data-approve="${c.id}">✓ APROVAR</button>`:`<button class="btn primary" ${next?`data-review="${next.id}"`:'data-nav="conteudos"'}>${next?'PRÓXIMO →':'CONCLUIR'}</button>`}</div>`;bindReview()}
function bindReview(){$$('[data-play]').forEach(b=>b.onclick=()=>{const c=state.contents.find(x=>x.id===b.dataset.play),box=b.parentElement;box.innerHTML=`<iframe src="${videoUrl(c)}" allowfullscreen></iframe>`});$$('[data-carousel-prev]').forEach(b=>b.onclick=()=>{state.carouselIndex[b.dataset.carouselPrev]=(state.carouselIndex[b.dataset.carouselPrev]||0)-1;renderReview()});$$('[data-carousel-next]').forEach(b=>b.onclick=()=>{state.carouselIndex[b.dataset.carouselNext]=(state.carouselIndex[b.dataset.carouselNext]||0)+1;renderReview()});$$('[data-carousel-to]').forEach(b=>b.onclick=()=>{state.carouselIndex[b.dataset.carouselTo]=Number(b.dataset.index);renderReview()});$$('[data-open-feedback]').forEach(b=>b.onclick=()=>{state.feedbackOpen=true;renderReview();setTimeout(()=>$('#reviewFeedback')?.focus(),50)});$$('[data-cancel-feedback]').forEach(b=>b.onclick=()=>{state.feedbackOpen=false;renderReview()});$$('[data-send-feedback]').forEach(b=>b.onclick=()=>{const ta=$('#reviewFeedback'),feedback=ta?.value.trim();if(!feedback)return toast('Descreva o ajuste primeiro');sendAction({action:'ALTERACAO',contentId:b.dataset.sendFeedback,feedback},'Alteração registrada')});$$('[data-approve]').forEach(b=>b.onclick=()=>sendAction({action:'APROVADO',contentId:b.dataset.approve},'Conteúdo aprovado'));$$('[data-copy]').forEach(b=>b.onclick=async()=>{const c=state.contents.find(x=>x.id===b.dataset.copy);await navigator.clipboard.writeText(c?.caption||'');toast('Legenda copiada')})}
function renderCalendario(){const arr=state.contents.slice().sort((a,b)=>display(a).date.localeCompare(display(b).date));$('#page-calendario').innerHTML=`${pageHead('Calendário','Datas previstas e status de cada peça.')}<section class="panel"><div class="calendar-list">${arr.map(c=>{const d=display(c);return `<button class="calendar-row" data-review="${c.id}"><time>${dateLong(d.date)}</time><img src="${thumb(c)}"><span>${typeChip(c)}<strong>${d.title}</strong><small>${d.person}</small></span>${statusBadge(c)}</button>`}).join('')}</div></section>`}
function renderArquivos(){const files=(state.config.files||[]).filter(f=>f.url&&f.url!=='#');$('#page-arquivos').innerHTML=`${pageHead('Arquivos','Somente materiais que realmente estão disponíveis.')}<section class="panel">${files.length?`<div class="file-grid">${files.map(f=>`<a class="file-card" target="_blank" href="${f.url}"><strong>${f.title}</strong><p>${f.description}</p><span>Abrir →</span></a>`).join('')}</div>`:'<div class="empty">Nenhum arquivo extra disponível neste momento.</div>'}</section>`}
function renderPage(p){if(p==='inicio')renderInicio();if(p==='conteudos')renderConteudos();if(p==='calendario')renderCalendario();if(p==='arquivos')renderArquivos()}
async function sendAction(payload,msg){try{toast('Registrando...');await fetch(state.config.backend,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...payload,projectKey:state.config.projectKey})});state.actions.push({contentId:payload.contentId,action:payload.action,feedback:payload.feedback||'',timestamp:'Agora'});state.feedbackOpen=false;toast(msg);renderReview();setTimeout(()=>loadData(true),1600)}catch(e){toast('Não foi possível registrar agora')}}
async function loadData(silent=false){try{const res=await fetch(`${state.config.backend}?key=${encodeURIComponent(state.config.projectKey)}&_=${Date.now()}`,{cache:'no-store'});const data=await res.json();if(!data.ok)throw new Error();state.contents=data.contents||[];state.actions=data.actions||[];state.lot=data.lot||'';if(state.reviewId)renderReview();else renderPage(state.page);if(!silent)toast('Portal sincronizado')}catch(e){if(!silent)toast('Portal aberto · sincronização indisponível')}}
async function init(){applyTheme();bindBase();renderNav();try{const r=await fetch(`${ROOT}clientes/${CLIENT}.json`,{cache:'no-store'});state.config=await r.json();$('#sideClient').textContent=state.config.name;$('#topClient').textContent=state.config.name.toUpperCase();renderPage('inicio');await loadData(true)}catch(e){$('#page-inicio').innerHTML='<div class="empty">Não foi possível carregar o portal.</div>'}}
init();