const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ROOT=document.body.dataset.root||'../../',CLIENT=document.body.dataset.client||'lavareda';
const NAV=[['inicio','Início'],['entregas','Entregas'],['calendario','Calendário'],['arquivos','Arquivos']],ICON={inicio:'⌂',entregas:'▤',calendario:'□',arquivos:'⌁'};
const DELIVERY={id:'08',title:'ENTREGA #08',start:'2026-09-01',end:'2026-09-05',estimate:6,contentIds:['HO-01','KP-01','VM-01','ES-01']};
const MEDIA={
'HO-01':{type:'reel',label:'REEL',orientation:'vertical'},
'KP-01':{type:'static',label:'ESTÁTICO',image:'1eOFPH5mYWFv79zhxC5VorGKnzVTCrXNx',title:'Gravidez de alto risco e benefício por incapacidade sem carência',date:'2026-09-02'},
'VM-01':{type:'carousel',label:'CARROSSEL',slides:['1r0fQRijZaMmrAVP1fgREq8EV_buNi6mt','1x_cx2gtECzvErlIPn8NQZQctH_EISNk_','1BOyJ9LsMl-ualKIDUBfc9n673SLkWaKN','1iLIKAe9yRRWAc_O7fVaHoxtn-BKO1L7r','1H4_yLgSdLAgOq9OELij0oqCP2SRZowCW'],title:'Cônjuge separado e dependência econômica para pensão militar',date:'2026-09-04'},
'ES-01':{type:'reel',label:'REEL',orientation:'vertical',date:'2026-09-05'}};
const state={config:null,contents:[],actions:[],lot:'',page:'inicio',reviewId:null,carousel:{},feedbackOpen:false,busy:false};
function mediaFor(c){const o=MEDIA[c.id]||{};let orientation=o.orientation;if(!orientation&&c.videoWidth&&c.videoHeight)orientation=+c.videoWidth>+c.videoHeight?'horizontal':'vertical';return{type:'reel',label:'REEL',orientation:orientation||'vertical',...o}}
function view(c){const m=mediaFor(c);return{...c,title:m.title||c.title,date:m.date||c.date,media:m}}
function thumbUrl(id,size='w1600'){return`https://drive.google.com/thumbnail?id=${id}&sz=${size}`}
function thumb(c){const d=view(c);if(d.media.type==='static')return thumbUrl(d.media.image);if(d.media.type==='carousel')return thumbUrl(d.media.slides[0]);return thumbUrl(c.coverId||c.videoId,'w1000')}
function videoUrl(c){return`https://drive.google.com/file/d/${c.videoId}/preview`}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function setTheme(m){localStorage.setItem('audaz-theme',m);applyTheme()}
function applyTheme(){const p=localStorage.getItem('audaz-theme')||'system',a=p==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):p;document.documentElement.dataset.theme=a;$$('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===p));document.querySelector('meta[name=theme-color]')?.setAttribute('content',a==='dark'?'#151514':'#e8e4d6')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2500)}
function dateObj(d){if(!d)return null;const[y,m,x]=d.split('-').map(Number);return new Date(y,m-1,x)}
function dateShort(d){const x=dateObj(d);return x?x.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','').toUpperCase():''}
function weekdayDate(d){const x=dateObj(d);return x?x.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).replace(/\./g,'').toUpperCase():''}
function statusFor(c){let s=c.initialStatus||'aguardando';state.actions.filter(a=>a.contentId===c.id).forEach(a=>{if(a.action==='APROVADO')s='aprovado';if(a.action==='ALTERACAO')s='alteracao'});return s}
function statusLabel(s){return s==='aprovado'?'Aprovado':s==='alteracao'?'Ajuste solicitado':'Aguardando você'}
function statusChip(c){const s=statusFor(c);return`<span class="status ${s}"><i></i>${statusLabel(s)}</span>`}
function typeChip(c){const m=mediaFor(c);return`<span class="type ${m.type}">${m.label}</span>`}
function deliveryContents(){const x=DELIVERY.contentIds.map(id=>state.contents.find(c=>c.id===id)).filter(Boolean);return x.length?x:state.contents.slice(0,4)}
function stats(){const items=deliveryContents(),approved=items.filter(c=>statusFor(c)==='aprovado'),changes=items.filter(c=>statusFor(c)==='alteracao'),pending=items.filter(c=>statusFor(c)==='aguardando');return{items,total:items.length,approved,changes,pending,reviewed:approved.length+changes.length}}
function deliveryStatus(){const s=stats();if(!s.reviewed)return'AGUARDANDO REVISÃO';if(s.reviewed<s.total)return'EM REVISÃO';if(s.changes.length)return'AJUSTES SOLICITADOS';return'CONCLUÍDA'}
function periodLabel(){return`${dateShort(DELIVERY.start)} — ${dateShort(DELIVERY.end)}`}
function breakdown(){const c={reel:0,carousel:0,static:0};deliveryContents().forEach(x=>c[mediaFor(x).type]++);return[c.reel&&`${c.reel} ${c.reel===1?'Reel':'Reels'}`,c.carousel&&`${c.carousel} ${c.carousel===1?'carrossel':'carrosséis'}`,c.static&&`${c.static} ${c.static===1?'estático':'estáticos'}`].filter(Boolean).join(' · ')}
function firstPending(){return deliveryContents().find(c=>statusFor(c)==='aguardando')||deliveryContents()[0]}
function nextPendingAfter(c){const a=deliveryContents(),i=a.findIndex(x=>x.id===c.id);return[...a.slice(i+1),...a.slice(0,i)].find(x=>statusFor(x)==='aguardando')||null}
function renderNav(){const h=NAV.map(([id,l])=>`<button class="nav-btn ${state.page===id?'active':''}" data-nav="${id}"><span>${ICON[id]}</span>${l}</button>`).join('');$('#sideNav').innerHTML=h;$('#drawerNav').innerHTML=h}
function navigate(p){state.page=p;state.reviewId=null;state.feedbackOpen=false;$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${p}`));$('#drawer').classList.remove('show');renderNav();renderPage(p);scrollTo({top:0,behavior:'smooth'})}
function openReview(id){state.reviewId=id;state.feedbackOpen=false;$$('.page').forEach(x=>x.classList.remove('active'));$('#page-revisao').classList.add('active');renderReview();scrollTo({top:0,behavior:'smooth'})}
function startReview(){const c=firstPending();if(c)openReview(c.id)}
function bindGlobal(){document.body.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)return navigate(n.dataset.nav);const r=e.target.closest('[data-review]');if(r)return openReview(r.dataset.review);if(e.target.closest('[data-start-review]'))return startReview()});$('#mobileMenu').onclick=()=>$('#drawer').classList.add('show');$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('show');$('#drawer').onclick=e=>{if(e.target===$('#drawer'))$('#drawer').classList.remove('show')};$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));$('#mobileTheme').onclick=()=>{const x=localStorage.getItem('audaz-theme')||'system';setTheme(x==='system'?'light':x==='light'?'dark':'system')}}
function hero(){const s=stats(),pct=s.total?Math.round(s.reviewed/s.total*100):0;return`<section class="delivery-hero"><div class="delivery-intro"><span class="collab">AUDAZ <i>×</i> ${esc(state.config.name.toUpperCase())}</span><span class="eyebrow">ENTREGA DA SEMANA</span><h1>${DELIVERY.title}</h1><div class="period">${periodLabel()}</div><p><strong>${s.total} conteúdos estão prontos para você.</strong><br>Reels, carrosséis e peças desta semana, organizados na ordem de publicação.</p><div class="delivery-meta"><span>${breakdown()}</span><span>~${DELIVERY.estimate} min para revisar</span></div><button class="btn primary hero-cta" data-start-review>${s.reviewed?'CONTINUAR REVISÃO':'COMEÇAR REVISÃO'} <b>→</b></button></div><aside class="delivery-progress"><div class="status-line"><span>STATUS</span><strong>${deliveryStatus()}</strong></div><div class="progress-number"><b>${s.reviewed}</b><span>de ${s.total}<br>revisados</span></div><div class="progress-track"><i style="width:${pct}%"></i></div><div class="progress-details"><span><b>${s.approved.length}</b> aprovados</span><span><b>${s.changes.length}</b> ajustes</span><span><b>${s.pending.length}</b> pendentes</span></div></aside></section>`}
function item(c,i){const d=view(c);return`<button class="delivery-item" data-review="${c.id}"><span class="item-number">${String(i+1).padStart(2,'0')}</span><img src="${thumb(c)}" alt=""><span class="item-copy">${typeChip(c)}<strong>${esc(d.title)}</strong><small>${weekdayDate(d.date)} · Publicação prevista</small></span>${statusChip(c)}<b class="item-arrow">→</b></button>`}
function renderInicio(){const s=stats();$('#page-inicio').innerHTML=`${hero()}<section class="section"><div class="section-head"><div><span class="eyebrow">NESTA ENTREGA</span><h2>${s.total} peças, uma revisão</h2></div><button class="text-btn" data-nav="entregas">Ver entrega →</button></div><div class="delivery-list">${s.items.map(item).join('')}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">PRÓXIMAS PUBLICAÇÕES</span><h2>Sua semana</h2></div><button class="text-btn" data-nav="calendario">Abrir calendário →</button></div><div class="week-strip">${s.items.map(c=>{const d=view(c);return`<button data-review="${c.id}"><span>${weekdayDate(d.date)}</span>${typeChip(c)}<strong>${esc(d.title)}</strong>${statusChip(c)}</button>`}).join('')}</div></section><footer class="signature"><span>AUDAZ × ${esc(state.config.name.toUpperCase())}</span><strong>UMA ENTREGA. TUDO NO LUGAR.</strong><p>${esc(state.config.headline||'')}</p></footer>`}
function pastDeliveries(){const b={};state.actions.forEach(a=>{const l=a.lot||'';if(!l||l===state.lot)return;b[l]||={};b[l][a.contentId]={title:a.title||a.contentId,action:a.action}});return Object.entries(b).map(([lot,items])=>({lot,items:Object.values(items)}))}
function renderEntregas(){const s=stats(),past=pastDeliveries();$('#page-entregas').innerHTML=`<header class="page-head"><span class="eyebrow">ENTREGAS</span><h1>Seu trabalho, organizado por ciclos.</h1><p>Cada entrega reúne o que foi preparado para um período e mantém as decisões no mesmo lugar.</p></header><article class="delivery-card current"><div><span class="eyebrow">ATUAL · ${deliveryStatus()}</span><h2>${DELIVERY.title}</h2><strong>${periodLabel()}</strong><p>${s.total} conteúdos · ${breakdown()}</p></div><div class="delivery-card-progress"><b>${s.reviewed}/${s.total}</b><span>revisados</span><button class="btn primary" data-start-review>${s.reviewed?'CONTINUAR':'COMEÇAR'} →</button></div></article><section class="section"><div class="section-head"><div><span class="eyebrow">CONTEÚDOS DA ENTREGA</span><h2>Ordem de publicação</h2></div></div><div class="delivery-list">${s.items.map(item).join('')}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">HISTÓRICO</span><h2>Entregas anteriores</h2></div></div>${past.length?`<div class="past-grid">${past.map(p=>`<article class="past-card"><span>${esc(p.lot)}</span><strong>${p.items.length} conteúdos registrados</strong><small>Histórico de decisões disponível</small></article>`).join('')}</div>`:`<div class="empty-history"><strong>O histórico começa aqui.</strong><p>À medida que novas entregas forem concluídas, elas aparecerão nesta área.</p></div>`}</section>`}
function media(c){const d=view(c),m=d.media;if(m.type==='static')return`<div class="image-view"><img src="${thumbUrl(m.image)}" alt="${esc(d.title)}"></div>`;if(m.type==='carousel'){const i=state.carousel[c.id]||0;return`<div class="carousel"><div class="carousel-main"><button data-slide-prev="${c.id}" ${i===0?'disabled':''}>←</button><img src="${thumbUrl(m.slides[i])}" alt="Slide ${i+1}"><button data-slide-next="${c.id}" ${i===m.slides.length-1?'disabled':''}>→</button><span>${i+1} de ${m.slides.length}</span></div><div class="carousel-thumbs">${m.slides.map((id,n)=>`<button class="${n===i?'active':''}" data-slide="${c.id}" data-index="${n}"><img src="${thumbUrl(id,'w300')}" alt=""></button>`).join('')}</div></div>`}return`<div class="video-wrap ${m.orientation}"><div class="video-frame ${m.orientation}"><button class="video-launch" data-play="${c.id}"><span>▶</span><strong>ASSISTIR REEL</strong><small>O player respeita o formato da peça.</small></button></div></div>`}
function dots(id){return deliveryContents().map(c=>`<i class="${c.id===id?'current':''} ${statusFor(c)!=='aguardando'?'done':''}"></i>`).join('')}
function decision(c){const s=statusFor(c);if(s==='aprovado')return`<aside class="decision"><span class="eyebrow">SUA DECISÃO</span><div class="decision-success">✓ <strong>APROVADO</strong><p>Esta peça já está liberada para seguir no fluxo.</p></div></aside>`;if(s==='alteracao')return`<aside class="decision"><span class="eyebrow">SUA DECISÃO</span><div class="decision-adjust">↻ <strong>AJUSTE REGISTRADO</strong><p>A Audaz recebeu sua solicitação. Você pode continuar revisando as outras peças.</p></div></aside>`;return`<aside class="decision"><span class="eyebrow">SUA DECISÃO</span><h3>Está tudo certo?</h3><p>Aprove em um toque. Se precisar mudar algo, descreva apenas o necessário.</p><button class="btn primary wide" data-approve="${c.id}">✓ APROVAR CONTEÚDO</button><button class="btn wide secondary" data-open-feedback="${c.id}">SOLICITAR AJUSTE</button><div class="feedback ${state.feedbackOpen?'show':''}"><label>O que precisa ser ajustado?</label><textarea id="feedbackText" placeholder="Ex.: aos 00:18, trocar a frase de abertura."></textarea><div><button class="text-btn" data-cancel-feedback>Cancelar</button><button class="btn primary" data-send-feedback="${c.id}">ENVIAR SOLICITAÇÃO</button></div></div></aside>`}
function renderReview(){const a=deliveryContents(),c=a.find(x=>x.id===state.reviewId);if(!c)return navigate('entregas');const d=view(c),i=a.findIndex(x=>x.id===c.id),s=stats();$('#page-revisao').innerHTML=`<div class="review-nav"><button data-nav="entregas">← Sair da revisão</button><div><strong>${i+1} de ${a.length}</strong><span class="dots">${dots(c.id)}</span></div><span>${s.reviewed}/${a.length} revisados</span></div><header class="review-title"><div>${typeChip(c)} ${statusChip(c)} <span class="version">V${esc(c.version||'1')}</span></div><h1>${esc(d.title)}</h1><p>${esc(d.person)} · <strong>${weekdayDate(d.date)}</strong> · Publicação prevista</p></header><div class="review-layout"><main><section class="media-card"><div class="media-head"><span>${d.media.label}</span><small>${d.media.type==='carousel'?'Revise todos os slides antes de decidir':'Confira a peça antes de decidir'}</small></div>${media(c)}</section><details class="caption-card" open><summary><span>LEGENDA</span><button type="button" data-copy="${c.id}">COPIAR</button></summary><div>${esc(c.caption||'Legenda ainda não adicionada.')}</div></details></main>${decision(c)}</div><div class="mobile-actionbar">${statusFor(c)==='aguardando'?`<button class="btn secondary" data-open-feedback="${c.id}">PEDIR AJUSTE</button><button class="btn primary" data-approve="${c.id}">✓ APROVAR</button>`:`<button class="btn primary" data-next-after="${c.id}">PRÓXIMO →</button>`}</div>`;bindReview()}
function renderCompletion(){const s=stats();$('#page-revisao').innerHTML=`<div class="completion"><span class="completion-check">✓</span><span class="eyebrow">ENTREGA REVISADA</span><h1>Obrigado, ${esc(state.config.name)}.</h1><p>Sua revisão desta semana foi concluída.</p><div class="completion-stats"><div><b>${s.approved.length}</b><span>APROVADOS</span></div><div><b>${s.changes.length}</b><span>AJUSTES SOLICITADOS</span></div><div><b>${s.reviewed}/${s.total}</b><span>REVISADOS</span></div></div><section class="what-next"><span class="eyebrow">O QUE ACONTECE AGORA</span><p>✓ Conteúdos aprovados seguem para publicação.</p><p>↻ Conteúdos com ajuste solicitado retornam para a Audaz.</p><p>✓ Você será avisado quando uma nova versão estiver disponível.</p></section><button class="btn primary" data-nav="inicio">VOLTAR AO PORTAL</button></div>`}
function bindReview(){$$('[data-play]').forEach(b=>b.onclick=()=>{const c=state.contents.find(x=>x.id===b.dataset.play);b.parentElement.innerHTML=`<iframe src="${videoUrl(c)}" allow="autoplay; fullscreen" allowfullscreen></iframe>`});$$('[data-slide-prev]').forEach(b=>b.onclick=()=>{state.carousel[b.dataset.slidePrev]=Math.max(0,(state.carousel[b.dataset.slidePrev]||0)-1);renderReview()});$$('[data-slide-next]').forEach(b=>b.onclick=()=>{state.carousel[b.dataset.slideNext]=(state.carousel[b.dataset.slideNext]||0)+1;renderReview()});$$('[data-slide]').forEach(b=>b.onclick=()=>{state.carousel[b.dataset.slide]=+b.dataset.index;renderReview()});$$('[data-open-feedback]').forEach(b=>b.onclick=()=>{state.feedbackOpen=true;renderReview();setTimeout(()=>$('#feedbackText')?.focus(),80)});$$('[data-cancel-feedback]').forEach(b=>b.onclick=()=>{state.feedbackOpen=false;renderReview()});$$('[data-approve]').forEach(b=>b.onclick=()=>decide(b,{action:'APROVADO',contentId:b.dataset.approve}));$$('[data-send-feedback]').forEach(b=>b.onclick=()=>{const f=$('#feedbackText')?.value.trim();if(!f)return toast('Descreva o ajuste primeiro');decide(b,{action:'ALTERACAO',contentId:b.dataset.sendFeedback,feedback:f})});$$('[data-next-after]').forEach(b=>b.onclick=()=>advance(state.contents.find(c=>c.id===b.dataset.nextAfter)));$$('[data-copy]').forEach(b=>b.onclick=async e=>{e.preventDefault();const c=state.contents.find(x=>x.id===b.dataset.copy);try{await navigator.clipboard.writeText(c?.caption||'');toast('Legenda copiada')}catch{toast('Não foi possível copiar')}})}
async function decide(button,payload){if(state.busy)return;state.busy=true;button.classList.add('pressed');const old=button.textContent;button.textContent=payload.action==='APROVADO'?'APROVANDO…':'ENVIANDO…';try{const r=await postAction(payload);state.actions.push({eventId:r.eventId||`local-${Date.now()}`,timestamp:r.timestamp||new Date().toLocaleString('pt-BR'),client:state.config.name,lot:state.lot,contentId:payload.contentId,action:payload.action,feedback:payload.feedback||'',statusAfter:payload.action==='APROVADO'?'aprovado':'alteracao'});toast(payload.action==='APROVADO'?'✓ Conteúdo aprovado':'✓ Ajuste registrado');state.feedbackOpen=false;renderReview();const c=state.contents.find(x=>x.id===payload.contentId);setTimeout(()=>advance(c),650)}catch(e){console.error(e);toast('Não foi possível registrar. Tente novamente.');button.textContent=old;button.classList.remove('pressed')}finally{state.busy=false}}
function advance(c){const n=nextPendingAfter(c);if(n)return openReview(n.id);if(stats().reviewed===stats().total)return renderCompletion();navigate('entregas')}
async function postAction(payload){const r=await fetch(state.config.backend,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...payload,projectKey:state.config.projectKey})}),d=await r.json();if(!d.ok)throw new Error(d.error||'backend');return d}
function renderCalendario(){const a=deliveryContents().slice().sort((x,y)=>view(x).date.localeCompare(view(y).date));$('#page-calendario').innerHTML=`<header class="page-head"><span class="eyebrow">CALENDÁRIO</span><h1>Planejamento da entrega.</h1><p>Uma visão ampliada das datas. A revisão continua acontecendo dentro de cada entrega.</p></header><section class="calendar-week">${a.map(c=>{const d=view(c);return`<button data-review="${c.id}"><time>${weekdayDate(d.date)}</time><img src="${thumb(c)}" alt=""><div>${typeChip(c)}<strong>${esc(d.title)}</strong><small>Publicação prevista</small></div>${statusChip(c)}</button>`}).join('')}</section>`}
function renderArquivos(){const f=(state.config.files||[]).filter(x=>x.url&&x.url!=='#');$('#page-arquivos').innerHTML=`<header class="page-head"><span class="eyebrow">ARQUIVOS</span><h1>Materiais quando você precisar.</h1><p>Esta área é secundária à revisão e reúne apenas recursos úteis do projeto.</p></header>${f.length?`<div class="files-grid">${f.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener"><span>${esc(x.type||'arquivo')}</span><strong>${esc(x.title)}</strong><p>${esc(x.description||'')}</p><b>ABRIR →</b></a>`).join('')}</div>`:`<div class="empty-history"><strong>Nenhum arquivo adicional nesta entrega.</strong><p>Os conteúdos para aprovação estão organizados em Entregas.</p></div>`}`}
function renderPage(p){if(p==='inicio')renderInicio();if(p==='entregas')renderEntregas();if(p==='calendario')renderCalendario();if(p==='arquivos')renderArquivos()}
async function load(){applyTheme();try{state.config=await fetch(`${ROOT}clientes/${CLIENT}.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('config');return r.json()});$('#sideClient').textContent=state.config.name;$('#topClient').textContent=state.config.name.toUpperCase();bindGlobal();renderNav();renderInicio();const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);try{const d=await fetch(`${state.config.backend}?key=${encodeURIComponent(state.config.projectKey)}`,{signal:ctl.signal,cache:'no-store'}).then(r=>r.json());clearTimeout(timer);if(!d.ok)throw Error(d.error||'backend');state.contents=d.contents||[];state.actions=d.actions||[];state.lot=d.lot||'';renderPage(state.page)}catch(e){clearTimeout(timer);console.error(e);$('#page-inicio').innerHTML=`<div class="load-error"><strong>Não conseguimos sincronizar a entrega.</strong><p>Atualize a página para tentar novamente.</p><button class="btn primary" onclick="location.reload()">TENTAR NOVAMENTE</button></div>`}}catch(e){console.error(e);$('.main').innerHTML='<div class="load-error"><strong>Não foi possível abrir este portal.</strong><p>Atualize a página ou tente novamente em instantes.</p></div>'}}
load();